# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQlQ4WOQdyz_0WarHrh2LqLzAmkNSpW9
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline

#Question 1:
a = np.arange(40,50)
b = np.arange(50,60)
plt.plot(a,b)
plt.title('Question 1')
plt.xlabel('a values')
plt.ylabel('b values')
plt.show()

#question 2:
#Plot a line plot showing the sales trend in company 1 and 2:
days = [1,2,3,4,5,6,7]
sales_1 = [160,150,140,145,175,165,180]
sales_2 = [70,90,160,150,140,145,175]
plt.plot(days,sales_1,'b-',color='g',label='sales of company 1')
plt.plot(days,sales_2,'r-',color='b',label='sales of company 2')
plt.title('Showing The Sales Trend In Company 1 and 2')
plt.xlabel("Days of the week")
plt.ylabel("Company Sales")
plt.legend()
plt.show()

#Question 3 
#Create a 3 by 3 subplots:multiple plots
x = [1,2,3,4]
y1 = [4,3,2,1]
y2 = [10,20,30,40]
y3 = [40,30,20,10]
y4 = [1,2,1,2]
y5 = [40,70,90,70]

plt.suptitle('CREATING SUB-PLOTS',fontsize=15)

plt.subplot(3,3,1)
plt.plot(x,y1,'r-')
plt.xlabel('X')
plt.ylabel('Y1')

plt.subplot(3,3,2)
plt.plot(x,y2,'r--')
plt.xlabel('X')
plt.ylabel('Y2')

plt.subplot(3,3,3)
plt.plot(x,y3,'g-')
plt.xlabel('X')
plt.ylabel('Y3')

plt.subplot(3,3,4)
plt.plot(x,y4,'go--')
plt.xlabel('X')
plt.ylabel('Y4')

plt.subplot(3,3,5)
plt.plot(x,y5,'bo--')
plt.xlabel('X')
plt.ylabel('Y5')
plt.show()